version: '3'
services:
  web:
    image: robinbachus/the-cloud-php:latest
    command: php -S 0.0.0.0:5000 -t /var/www/html/
    ports:
      - 5000:5000
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
  db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=""
      - MYSQL_DATABASE=rolodex
      - MYSQL_USER=RobinB
      - MYSQL_PASSWORD=Testtest123!!
    volumes:
      - ./db_data:/var/lib/mysql