name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DH_USER }}
        password: ${{ secrets.DH_PASS }}

    - name: Build and push Docker image
      run: |
            docker build -t robinbachus/the-cloud-php:latest .
            docker push robinbachus/the-cloud-php:latest
